# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    - id: run-make-checks
      name: Run make clean and build
      entry: bash -c 'if [ -z "$CI" ]; then make clean all; else echo "Skipping make build in CI"; fi'
      language: system
      pass_filenames: false
      files: ^(shadowfax/|common/|tsm/|Cargo\.toml|Cargo\.lock)  # Only trigger if Rust files or Cargo files change
