ROOT                := ../..
LAUNCHER_NAME       := two-tvms
LAUNCHER_METADATA   := 1M
GUEST_MEMORY_SIZE   ?= 4194304
GUEST_MEMORY_COUNT  := 2
PAYLOAD_SRC         := guest.c

include $(ROOT)/guests/bare-metal/launcher.mk
